### ISSUE TITLE
Capture sound from a mac microphone

### ISSUE THREAD

**Issue by first-developer** [andrewrk/node-sox#4]
Hi,
Again thank for this great npm package! you definitly rock :+1: 
However , I got one question: is it possible using this library, to capture the sound coming from the  microphone of my Mac ? 
If not, do you have any idea of how I can perfrom this action? 
Thanks in advance

Best regards

**Comment by andrewrk** [comment]
>  is it possible using this library, to capture the sound coming from the microphone of my Mac ? 

No. I'm afraid it's a rather special-case library, useful only for transcoding and identification.

> If not, do you have any idea of how I can perfrom this action? 

I am not aware of a good solution. The sox binary might be able to do it; you might try executing it as a child process directly.

I'm going to close this issue as adding sound capture is not planned.
